/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobiblioteca.Telas;

/**
 *
 * @author marcia
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastroAutor = new javax.swing.JMenuItem();
        menuLivro = new javax.swing.JMenuItem();
        menuPessoa = new javax.swing.JMenuItem();
        Movimento = new javax.swing.JMenu();
        movEmprestimo = new javax.swing.JMenuItem();
        movDevolucao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        menuCadastroAutor.setText("Cadastro autor");
        menuCadastroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroAutorActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastroAutor);

        menuLivro.setText("Cadastro livro");
        menuLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLivroActionPerformed(evt);
            }
        });
        jMenu1.add(menuLivro);

        menuPessoa.setText("Cadastro pessoa");
        menuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(menuPessoa);

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleName("Cadastro");

        Movimento.setText("Movimento");

        movEmprestimo.setText("Emprestimo");
        movEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movEmprestimoActionPerformed(evt);
            }
        });
        Movimento.add(movEmprestimo);

        movDevolucao.setText("Devolucao");
        movDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movDevolucaoActionPerformed(evt);
            }
        });
        Movimento.add(movDevolucao);

        jMenuBar1.add(Movimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroAutorActionPerformed
        FrmAutor frm = new FrmAutor();
        frm.setVisible(true);
    }//GEN-LAST:event_menuCadastroAutorActionPerformed

    private void menuLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLivroActionPerformed
        FrmLivro frm = new FrmLivro();
        frm.setVisible(true);
    }//GEN-LAST:event_menuLivroActionPerformed

    private void menuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoaActionPerformed
        FrmPessoa frm = new FrmPessoa();
        frm.setVisible(true);
    }//GEN-LAST:event_menuPessoaActionPerformed

    private void movEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movEmprestimoActionPerformed
        FrmEmprestimo frm = new FrmEmprestimo();
        frm.setVisible(true);
    }//GEN-LAST:event_movEmprestimoActionPerformed

    private void movDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movDevolucaoActionPerformed
        FrmDevolucao frm = new FrmDevolucao();
        frm.setVisible(true);
    }//GEN-LAST:event_movDevolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Movimento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadastroAutor;
    private javax.swing.JMenuItem menuLivro;
    private javax.swing.JMenuItem menuPessoa;
    private javax.swing.JMenuItem movDevolucao;
    private javax.swing.JMenuItem movEmprestimo;
    // End of variables declaration//GEN-END:variables
}
